BIN_NAME=fxchaind
FXCHAIN_TOP=${GOPATH}/src/github.com/gridfx/fxchain
FXCHAIN_BIN=${FXCHAIN_TOP}/build
FXCHAIN_BIN=${GOPATH}/bin
FXCHAIN_NET_TOP=`pwd`
FXCHAIN_NET_CACHE=${FXCHAIN_NET_TOP}/cache
CHAIN_ID="clockend-4200"


BASE_PORT_PREFIX=26600
P2P_PORT_SUFFIX=56
RPC_PORT_SUFFIX=57
REST_PORT=8545
let BASE_PORT=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedp2pport=${BASE_PORT_PREFIX}+${P2P_PORT_SUFFIX}
let seedrpcport=${BASE_PORT_PREFIX}+${RPC_PORT_SUFFIX}
let seedrestport=${seedrpcport}+1
